import { FrontendPluginError } from "../../resources/errors";
export declare enum ErrorType {
    User = 0,
    System = 1
}
export declare class BlazorPluginError extends FrontendPluginError {
    innerError?: Error;
    constructor(errorType: ErrorType, code: string, message: string, suggestions: string[], helpLink?: string, innerError?: Error);
    getMessage(): string;
    setInnerError(error: Error): void;
    getInnerError(): Error | undefined;
}
export declare class FetchConfigError extends BlazorPluginError {
    constructor(key: string);
}
export declare class ProvisionError extends BlazorPluginError {
    constructor(resource: string, innerErrorCode?: string);
}
export declare class ConfigureWebAppError extends BlazorPluginError {
    constructor(innerErrorCode?: string);
}
export declare class ProjectPathError extends BlazorPluginError {
    constructor(projectFilePath: string);
}
export declare class BuildError extends BlazorPluginError {
    constructor(innerError?: Error);
}
export declare class ZipError extends BlazorPluginError {
    constructor();
}
export declare class PublishCredentialError extends BlazorPluginError {
    constructor();
}
export declare class UploadZipError extends BlazorPluginError {
    constructor();
}
export declare const UnhandledErrorCode = "UnhandledError";
export declare const UnhandledErrorMessage = "Unhandled error.";
export declare function runWithErrorCatchAndThrow<T>(error: BlazorPluginError, fn: () => T | Promise<T>): Promise<T>;
export declare function runWithErrorCatchAndWrap<T>(wrap: (error: any) => BlazorPluginError, fn: () => T | Promise<T>): Promise<T>;
//# sourceMappingURL=errors.d.ts.map